### ISSUE TITLE
Add accessible names for comment form fields

### ISSUE THREAD

**Issue by dev-nicolaos** [lowercasename/gathio#100]
Currently, the `<input>` and `<textarea>` elements in the event discussion section do not have [accessible names](https://www.w3.org/WAI/ARIA/apg/practices/names-and-descriptions/), instead relying on the browser to fallback to the placeholder text. This is generally considered bad practice as the text disappears once the user begins typing and the web platform provides dedicated ways to give a form field an accessible name (`<label>`, `aria-label` or `aria-labelledby`).

I can submit a PR to address this if it would be accepted. I'd add a `<label>` for each unless there is a strong objection to visual labels from the maintainer, in which case `aria-label` would be better than nothing. Visual labels are preferred from an A11y standpoint (see Rule 2 on the link above).

One other small UX thing (I can submit a second issue for this if its preferred): IMHO it'd make for sense for the comment's placeholder to say "What would you like to say?" rather than "What would you like to ask?" since there isn't any reason the user's comment has to be a question.

**Comment by lowercasename** [comment]
This would be super - both useful and long overdue! I suspect that there are other fields on the site without properly linked `label` elements that would also benefit from their addition. Happy for that change to the placeholder text too.
