### ISSUE TITLE
Ability to add static content/pages in the footer (impressum, privacy)

### ISSUE THREAD

**Issue by Menrath** [lowercasename/gathio#109]
Feature request:

I would love to self host this for our community, but in most EU-countries we need to have contact data available to the person hosting the site, usually called impressum. In the same manner we need to have a privacy-policy available.

**Comment by lowercasename** [comment]
Hi, this sounds like a really useful idea - thanks for suggesting it! The main issue at the moment is that Gathio doesn't have an admin panel of any kind - configuration is handled by a simple file - and this sounds like it would require at least a basic admin panel. The other option I see is just having a simple directory of Markdown files, which the server can read from and assemble into links for the footer.

I'm not against either of these options, but the first one feels like quite a big project. Perhaps something for the backburner, or a good project for someone else to pick up!

**Comment by Menrath** [comment]
As this information rarely changes, configuring it via the config file or static files, maybe even in plain html that the service picks up, would be perfectly fine if well documented.

**Comment by lowercasename** [comment]
You caught me on a good morning (I'm recovering from Covid 👀 ) so I set up this functionality! Thank you for the inspiration, it was fun!
