### ISSUE TITLE
Make use of discoverable and indexable features

### ISSUE THREAD

**Issue by Menrath** [lowercasename/gathio#116]
## Problem Description

Usually events should only be visible to people having received the link. But for example if I follow an Event on my mastodon instance, because I have received the link, anyone on my mastodon instance can search for events on that gancio instance that are already followed by another user. I discovered that by typing `@gathio` in the post creation field, as the gathio instances domain also starts with `gathio.*`. So not the search field is the issue, but the autocreation API in the post creation field.

Screenshot explaining it more clearly:
![grafik](https://github.com/lowercasename/gathio/assets/99024746/4b6bf718-eeac-49dc-9a2d-4db3bca2e803)
The user currently logged in does not follow the gathio event user, of course. 

## Possible Improvements

Make use of Mastodons `toot:indexable` and `toot:discoverable` and set them to false. **I don't know if this is a solution** but would be most certainly an improvement. **If this is no solution** and Mastodon is still leaking this information I think the bigger **issue lies within Mastodon**, it should not include Profiles in the search/autocomplete results that are not discoverable and indexable when you haven't entered a single term of the username, only the domain. I'll search for an open issue over there as well or open a new one.

Example:

```json
{
	"@context": [
		"https://www.w3.org/ns/activitystreams",
		"https://w3id.org/security/v1",
		{
			"toot": "http://joinmastodon.org/ns#",
			"discoverable": "toot:discoverable",
			"indexable": "toot:indexable"
		}
	],
	"id": "https://gathio.graz.social/RE5njA5tjPhBucXTE2qpr",
	"type": "Person",
	"preferredUsername": "RE5njA5tjPhBucXTE2qpr",
	"inbox": "https://gathio.graz.social/activitypub/inbox",
	"outbox": "https://gathio.graz.social/RE5njA5tjPhBucXTE2qpr/outbox",
	"followers": "https://gathio.graz.social/RE5njA5tjPhBucXTE2qpr/followers",
	"summary": "<p><p>Wir essen Kuchen.</p>\n</p><p>Location: Morelli.</p><p>Starting 26 October 2023 2:00 pm Europe/Vienna.</p>",
	"name": "Testevent",
	"featured": "https://gathio.graz.social/RE5njA5tjPhBucXTE2qpr/featured",
	"discoverable": false,
	"indexable": false,
	"publicKey": {
		"id": "https://gathio.graz.social/RE5njA5tjPhBucXTE2qpr#main-key",
		"owner": "https://gathio.graz.social/RE5njA5tjPhBucXTE2qpr",
		"publicKeyPem": "-----BEGIN PUBLIC KEY-----\nMIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEAs+whl85rbJ0Df/fUNgIB\nXppkvoLa3j4DmBgMYQ3CSkIyXo94+VlwCviL+sPexWFQSmzMFjwYEQTO4Eg62xC4\ncWt4VlEu4hpw08OSUbCPaYEVQRHZfGqT4z7JNtU3b3w723TWaVtCtdaPZLCIRybx\nTWBu3hgk9RVRvTh4e24IGhg3l15fSIiy14uSh0KCiv6tvLhytwRI1afVwryurL9S\nBoPSBTk2Dx497f6rsjlXU0tW+xuyf1EmWIJZKOIOfYUnUCqd8CfgJy47zNzqQdHU\nJsgjLDCvEuF+3eBIIuoZPy0RMLOQUi2l5lvpSb5S6qFJB4ZA2XQ1dv/9yhninTdY\n+voPgFAHwZu1MuGg47V5zgPmYkubwv8ZFA3YhK1+CNDMx/UdAgauZAax76lx4bJN\nJ3fJR/evr0LE7OFmcNxjaAfQxkXaYa1CxSfzLwpWqF6jh890xD8hmvAldlD9Fbms\nSh1KtNg2Hl6y4qpL9idQ1es+UDg1RQLCLYj54R3cD0KqeigAcgw3ibHlgXnsgkfb\nEO4jny8wOv6+pgDWHPaHJ2d4KCE1Zev+sbD5nWOsoIRBjk4jyS22UEfophXUtxKo\nxppcGOGmJltogwK61Lhh0+yDKFxJ/5IkPTGSW1kVtFlAh97NOL35S9blawQziazQ\nd9CJ96UOZdKmtOJegs5YstUCAwEAAQ==\n-----END PUBLIC KEY-----\n"
	},
	"icon": {
		"type": "Image",
		"mediaType": "image/jpg",
		"url": "https://gathio.graz.social/events/RE5njA5tjPhBucXTE2qpr.jpg"
	}
}
```

Also see:
https://codeberg.org/fediverse/fep/src/branch/main/fep/5feb/fep-5feb.md

**Comment by lowercasename** [comment]
Agreed, this seems like a good addition to the AP payload. A bit annoying that Mastodon keeps coming up with fun variations on the AP standard! @dariusk, can you see any issues with this addition (setting `toot:indexable` and `toot:discoverable` to `false`?)

**Comment by dariusk** [comment]
I see no issue with adding this! I will make a PR.
