### ISSUE TITLE
Integrate Gathio into Signal App

### ISSUE THREAD

**Issue by kranebitt** [lowercasename/gathio#120]
I recently posted a Github Project for an idea for a privacy preserving peer2peer event app that allows to connect directly to your phone's calendar. I posted the idea under this link: https://github.com/kranebitt/sobremesa 

It became more and more clear that acutally it would be best to enhance an existing messenging app already in use with the event app on top of it in order to take advantage of the network effects. So I proposed to implement such a feature on top of the open source Signal Messenger: (https://community.signalusers.org/t/a-peer-to-peer-event-and-activity-function-application-on-top-of-signal/57513 )

A user there thankfully pointed out your project to me. It would be great to follow up on the idea.

**Comment by lowercasename** [comment]
What a fun idea! I have no idea how building an app on top of Signal would work (does Signal have plugins or similar?), but Gathio has API endpoints (which I am slowly improving) with which a third party app could theoretically integrate. There'll even be docs after the TypeScript migration is nearer to done.

One thing Gathio doesn't do at the moment is discoverability of events (that's not the remit of the service, really). So an idea involving a map and browseable events would need to go to through some considerations about privacy.

**Comment by kranebitt** [comment]
Thank you :) It would definitely be fun to implement it. 

Regarding your questions, as far as I found out @signalapp does not have any plugin function and I am lacking the tech knowledge to know if this helps: https://github.com/signalapp/Signal-Desktop/issues/4869
Or this: https://github.com/signalapp/libsignal-service-java
But most likely Signal Foundation would have to implement some sort of Gathio feature within its UX. Maybe you could support the post in the Signal community forum or state your openness to help with a possible implementation. 

Thank you also for the considerations on discoverability of events and the considerations on privacy. This should certainly be further elaborated before introducing it. Certainly some limitations should be placed before implementing the feature. Restriction to large enough areas, visibility of event infos only for @singalapp contacts of the event organizer etc. 

Regarding my original concept on Github (https://github.com/kranebitt/sobremesa), I think Gathio covers enough of that in order to reference to Gathio directly. Let me know if you know any elegant way to do so.

**Comment by lowercasename** [comment]
I'm going to close this issue since I want to keep the issue tracker focused on current issues with Gathio and immediate improvements.
