### ISSUE TITLE
Feature Request - Integration of Signal CLI into Gath.io Event App

### ISSUE THREAD

**Issue by kranebitt** [lowercasename/gathio#121]
### Description:

I propose the integration of a send via Signal messenger function in Gath.io using [Signal CLI](https://github.com/AsamK/signal-cli.git). This feature would allow the app to send event notifications via Signal, providing users with an additional method of receiving updates. This would make the 

### Feature Details:

1. **Signal CLI Dependency:** The app would need to include the Signal CLI dependency.

2. **Notification Service Update:** The NotificationService class would need to be updated to include a method for sending notifications via Signal.

3. **Signal Configuration Properties:** The `application.properties` file would need to include properties for configuring Signal CLI.

4. **Testing:** Tests would need to be updated or added to cover the new functionality.

### Benefit:

This feature would enhance the user experience by providing an additional, secure method of receiving event notifications. Users who prefer Signal for communication would greatly benefit from this feature.

I kindly request the maintainers to consider this feature for future development. Thank you for considering this proposal.

**Comment by lowercasename** [comment]
Thanks for the suggestion, but I'm not interested in this - the Signal CLI app is Java-based, for starters, which would hugely increase the size of what is currently a simple TypeScript app. Is the list of features written by ChatGPT? It feels like it, since a quick search would tell you there isn't an `application.properties` file in the app.

**Comment by kranebitt** [comment]
Thank you. I appreciate the feedback. So I will continue to copy and paste event links manually.
Yes, not having web development skills myself, I asked ChatGPT for help.
