### ISSUE TITLE
Participant mail as mandatory field

### ISSUE THREAD

**Issue by Tealk** [lowercasename/gathio#122]
Hi,

Is it possible to set the mail field for the participants as a mandatory field?
This could help to prevent spam if you first have to confirm your participation by e-mail.

**Comment by lowercasename** [comment]
A lot of people probably don't want to give their emails out, and I'd rather keep the email aspect of Gathio as optional as possible for that reason, so I'm going to keep the functionality as it is. The validation-by-email aspect will also require a bit more extra code in the backend than I currently have time to write.

I can see some utility in making this a configurable option, so you're very welcome to submit a PR with this feature!

**Comment by Tealk** [comment]
Then I don't see it as a serious option for event planning.
If 500 people register but there are only 3 real users among them, the whole thing makes no sense.
