### ISSUE TITLE
Return ActivityPub object if request contains ActivityPub media type in Accept header

### ISSUE THREAD

**Issue by silverpill** [lowercasename/gathio#125]
ActivityPub spec says that implementations must use `application/ld+json; profile="https://www.w3.org/ns/activitystreams"` media type when retrieving objects:

https://www.w3.org/TR/activitypub/#retrieving-objects

However, gath.io returns HTML in that case. Example:

```shell
curl -H 'Accept: application/ld+json; profile="https://www.w3.org/ns/activitystreams"' https://gath.io/NGZbcJdlFjFRYkXlyyXhx
```

Only `application/activity+json` works:

```shell
curl -H 'Accept: application/activity+json' https://gath.io/NGZbcJdlFjFRYkXlyyXhx
```

**Comment by lowercasename** [comment]
This is a great catch, thank you, and is a good first step in my planned work on the AP library. I've made a PR for it here which I want to test against Mastodon before merging, so bear with me. https://github.com/lowercasename/gathio/pull/127

**Comment by lowercasename** [comment]
This is merged in and running on production!

**Comment by silverpill** [comment]
Thank you! It's working
