### ISSUE TITLE
RFE : make email optional for participants

### ISSUE THREAD

**Issue by MagicFab** [lowercasename/gathio#14]
The email address should not be required when indicating attendance.
This would make it easier for organizers to have an idea of how many people attend without having any identifiable information.

**Comment by lowercasename** [comment]
Event administrators can remove anyone they choose without supplying their email, although the person removed does get an email notifying them of this.

**Comment by MagicFab** [comment]
The use case here is where no email confirmations are needed nor wanted and keeping the email is not needed.
I can add a disclaimer to not use a personal identifiable email, suggestions where to obtain such accounts (ProtonMail ?) as an alternative, but it would make it easier for organizers to have the option to have events without any email retention.
The link to edit or remove yourself from the event could be shown once at registration time with clear indication it's the only way to remove yourself, won't be sent otherwise.

**Comment by ahstro** [comment]
A password could be randomly generated on the client side when clicking attend, saved on the server, and shown to the user with a note to keep it somewhere if they want to edit. Not sure if this is overkill or confusing, but it's a way to do it without requiring an email address

**Comment by MagicFab** [comment]
> A password could be randomly generated on the client side when clicking attend, saved on the server, and shown to the user with a note to keep it somewhere if they want to edit. Not sure if this is overkill or confusing, but it's a way to do it without requiring an email address

Yes, this would be a very good compromise! Making email optional, then generating some unique code to be kept in case one wants to remove attendance confirmation.

**Comment by lowercasename** [comment]
This is now implemented in https://github.com/lowercasename/gathio/commit/913f3d764547bb36ead71922f6dfac9e83f16c62, thanks for the suggestions all and feel free to tweak it.
