### ISSUE TITLE
Feature request: Hide "Edit" and "New" Buttons in Public Share Link Pages

### ISSUE THREAD

**Issue by candideu** [lowercasename/gathio#140]
Hi! Thank you for making this wonderful lightweight app! I've been using it to create quick little event pages for gatherings with friends.

My only suggestion would be to hide the big green "Edit' and "New" buttons, or provide a separate share link which doesn't have them. The buttons seem to confuse guests into thinking they've accessed the backend because of their prominence.

**Comment by lowercasename** [comment]
What about something like this, if you've got a public link without the edit token? (This has some new button styles, too).

<img width="980" alt="Screenshot 2024-03-04 at 12 00 17" src="https://github.com/lowercasename/gathio/assets/1748384/e227da81-591b-434b-aca8-052aef8486ef">

With hiding the 'New' button, I presume you're talking about situations where creating events is limited to a whitelist of email addresses? I suppose I could do the same sort of thing there, but I'm not sure where else I'd put it in the UI.

**Comment by lowercasename** [comment]
I've decided to go with this:

<img width="1218" alt="Screenshot 2024-05-26 at 16 57 28" src="https://github.com/lowercasename/gathio/assets/1748384/c313feda-b4a6-4016-8012-27c59b87a325">

I changed 'New' to 'Create an event', which helps suggest that the user can create their _own_ event, and moved the edit button when you're not authorised to edit the event into the right-hand side panel.

**Comment by candideu** [comment]
Looking good! Thank you for hearing me out!
