### ISSUE TITLE
internal server error after unattending event

### ISSUE THREAD

**Issue by ligi** [lowercasename/gathio#141]
![image](https://github.com/lowercasename/gathio/assets/111600/93565f2e-22cf-4a39-a3bc-1a25fbab3660)

**Comment by lowercasename** [comment]
Could you give me some more information - what sort of attendee is this? Did they attend via ActivityPub or the site? Did they have an email address? Can other attendees, like a test attendee you create, successfully unattend?

**Comment by ligi** [comment]
It's quite reproducible - you can reproduce it here:
 https://gath.io/q3vQ6xONvMqgS61niV3Ok

Maybe it is because the event is in the past?

**Comment by lowercasename** [comment]
Weird, I can add and remove my test attendee from that event with no problems, whether they have an email address set or not. And Gathio isn't logging any errors, probably because that 500 response is uncaught by the backend. I'll dig into this.

**Comment by lowercasename** [comment]
Oh, hold up - are you sending a removal password when you try and remove an attendee? I just realised I send a 500 error in that case and don't do anything with it on the frontend, which is not very helpful!
