### ISSUE TITLE
Remove participation through link without entering password

### ISSUE THREAD

**Issue by Konki1999** [lowercasename/gathio#145]
First of all, I really love the project. 

Would it be possible to implement a feature where in the RSVP confirmation email there is a link that takes you directly to the event page with a popup asking if you rely want to remove yourself from the participants list, without requiring the user to enter the deletion password? I imagine the password could be embedded in the relevant URL in some way. My girlfriend found the entire deletion password thing off-putting, and was afraid it would be too difficult for her not-so-techy friends to use.

**Comment by lowercasename** [comment]
This is now live!
