### ISSUE TITLE
URLs are not validated when editing an event

### ISSUE THREAD

**Issue by 08e57pg6cz** [lowercasename/gathio#149]
URLs are validated when creating an event, but not when editing an event. See how the links have become internal when I skipped the http/s part (screenshots in 20

1. Creating an event
![image](https://github.com/lowercasename/gathio/assets/126486511/9e46f98f-2cbe-46e0-8186-4b9952aee2f5)

2. Editing an event
![image](https://github.com/lowercasename/gathio/assets/126486511/4a43d04f-37fc-4c5c-ae4a-918f1cceb4d1)
![image](https://github.com/lowercasename/gathio/assets/126486511/ab0a860e-3b54-4c84-a22a-41ce93208d3e)

**Comment by lowercasename** [comment]
Good spot, this needs fixing!
