### ISSUE TITLE
text boxes arn't resizable

### ISSUE THREAD

**Issue by halkeye** [lowercasename/gathio#152]
I'm not sure if its because firefox or what, but the description is tiny, and since style is resize: none, you can't expand it at all

![image](https://github.com/lowercasename/gathio/assets/110087/38ad515a-4056-46d2-a9cf-7f539953f1b8)

is this intentional? a bug in firefox?

do you want a pr to remove resize?

**Comment by dev-nicolaos** [comment]
Not sure if this addresses the issue, but the text area does expand as you enter more text (either hitting enter or having the line wrap).

Also doesn't seem like the behavior is specific to Firefox. Box behaves identically in Brave (which is chromium based).

**Comment by halkeye** [comment]
oh it does! but doesn't do it on page load 🤔 

maybe the https://www.jacklmoore.com/autosize/#faq-hidden solution for resizing on focus is a solution? It didn't occur to me that I had to type something first. I was curious why i didn't notice when i first create the event though.

**Comment by lowercasename** [comment]
This is fixed, thanks for letting me know!
