### ISSUE TITLE
feature request: auto-populate "Ends" date

### ISSUE THREAD

**Issue by gerbrent** [lowercasename/gathio#157]
For usability, it would be helpful to auto-populate the "Ends" date with the "Starts" date, given many events start and end on the same date.

![image](https://github.com/lowercasename/gathio/assets/7018928/1c3ef605-eba6-4f16-909f-39c0b9ae3fef)

**Comment by lowercasename** [comment]
Great idea - implemented in https://github.com/lowercasename/gathio/commit/68f5ce96ee19c77d46ddcdd18eefad6257cd47fa!
