### ISSUE TITLE
Provide tagged releases

### ISSUE THREAD

**Issue by ahstro** [lowercasename/gathio#16]
Hey :relaxed: I'm trying to package gathio for [YunoHost](https://yunohost.org/), but it requires downloading a `zip` or `tar.gz` and validating towards a checksum. The only way for me to do this right now is to download `https://github.com/lowercasename/gathio/archive/master.tar.gz`, those checksum is going to change, and thus break installations, with every commit.

Would you consider providing tagged releases so packaging gathio is less of a hassle? :innocent:

**Comment by lowercasename** [comment]
Hi! Thank you so much for your interest, and yes, that's a great idea - I will first learn how to do this, then do it. ;)

**Comment by palfrey** [comment]
https://stackoverflow.com/a/18223354/320546 is a good guide on doing this

**Comment by palfrey** [comment]
@ahstro I'd also note that if you browse to a specific commit, then click Clone/Download, the download.zip is for a specific commit. e.g. current master is https://github.com/lowercasename/gathio/archive/0c46e2d2d148efb7cfabcf82c12266a8d788f551.zip

**Comment by lowercasename** [comment]
This is now set up, thanks for the help :)
