### ISSUE TITLE
My event is gone

### ISSUE THREAD

**Issue by JimsTools** [lowercasename/gathio#164]
It's not 7 days past my event date, but my event is no longer available.
[https://gath.io/6a3pzRy7FEZC8QxB_2Gx_](https://gath.io/6a3pzRy7FEZC8QxB_2Gx_)

**Comment by lowercasename** [comment]
Hi there! Sorry about this, the MongoDB database on the main server has been crashing under high load. It's back up now! Just give me a shout if it happens again.
