### ISSUE TITLE
Gathio deleting events before start date`

### ISSUE THREAD

**Issue by 26VirenS** [lowercasename/gathio#169]
I have been using Gathio to coordinate sign ups and its been great. Lately though, my events have started disappearing. I get an email saying "you have been removed from the event" and go to see a 404 error saying my event doesn't exist.

**Comment by asos-tommycouzens** [comment]
Hi, this has happened to me too. I created a detailed event with custom art that isn't util the 7th September, some people have RSVP'd, but the event now is 404ing for everyone on the normal URL and also for me on the admin URL. :(

Please fix as I love using gathio but this makes it unusable!

**Comment by lowercasename** [comment]
Hi both, I'm so sorry about this - there's been an intermittent issue with the database where it's been losing data while running in Docker, which I'm trying to understand and fix. I've just restored an automatic backup from 1 August, but I'm very sorry to say all events made since then have been deleted. I'll keep you posted!

**Comment by asos-tommycouzens** [comment]
Thanks for the speedy response! Do you think this will keep happening or will I be safe to remake the event now and not face deletion?

**Comment by lowercasename** [comment]
The public Gathio server was attacked by ransomware, which is why the database was deleted. More information in this Mastodon thread: https://hachyderm.io/@lown/112948571960024349

I've taken the server offline while I get this sorted.

**Comment by lowercasename** [comment]
This has now been resolved! More info here: https://hachyderm.io/@lown/112968201391118617
