### ISSUE TITLE
Option to download ICS file

### ISSUE THREAD

**Issue by rsmoz** [lowercasename/gathio#20]
Would be nice to have this option for non-Google Calendar users.

https://en.wikipedia.org/wiki/ICalendar

**Comment by lowercasename** [comment]
Good idea - I'll do this when I next do some work on gathio unless someone else wants to throw some code together.

**Comment by lowercasename** [comment]
This is now in https://github.com/lowercasename/gathio/commit/60d99e4d35568b3fb76eb26f0284236b4cd602c3!
