### ISSUE TITLE
Use longer event identifiers

### ISSUE THREAD

**Issue by rsmoz** [lowercasename/gathio#21]
Event random identifiers should perhaps be longer to make it impossible to bruteforce identifiers en masse, which an attacker could do to harvest users’ addresses over time.

**Comment by lowercasename** [comment]
This is a valid concern - I also like the short URLs that it currently generates in terms of looks, however. One thing I'll say is that on the tiny server which currently hosts gathio, a bruteforce attack will most likely just crash the server, which is ironically a good defence? Do you know how long an identifier should be to make bruteforcing pointless?

**Comment by dariusk** [comment]
The`shortid` module is pretty bad for security generally -- an alternative is [nanoid](https://github.com/ai/nanoid) which produces by default IDs that look like this: `V1StGXR8_Z5jdHi6B-myT`.

Longer than what you have right now but security-minded people seem to like it a lot better, and it seems like it would be pretty easy to drop in.

**Comment by lowercasename** [comment]
That sounds good to me - what do we think about a server-side config option to switch between the two? Or is it best not to leave this vector of attack open? (I would switch the server to `nanoid` in any case).

**Comment by dariusk** [comment]
The current administrator of `shortid` [recommends that people switch to nanoid](https://github.com/dylang/shortid/issues/152#issuecomment-558994659) and that shortid has fundamental architectural problems that should be avoided.

**Comment by lowercasename** [comment]
Oh, that solves that question! I've just seen that nanoid supports shorter strings, so at some point I could set up a config option to choose the identifier length.

**Comment by bremensaki** [comment]
Is there any way this could involve adding human-pronounceable URLs in any way, even if they get much, much longer? I'm thinking about being able to add event links to posters or flyers where people might need to type them in, say gath.io/CorrectHorseBatteryStaple 

Generating a QR code from event URL as a PNG or something for download might also be a nice option for sharing them out but that's a whole other thing I guess.

**Comment by lowercasename** [comment]
I've switched shortid over to nanoid in this PR: https://github.com/lowercasename/gathio/pull/34

I haven't done anything about human-pronounceable URLs yet, and I'd like to see what people think either way. Could it be an option where people could give their events a specific named link (like https://gath.io/fun-picnic-day), as long as they're aware that, of course, it would make their event very easy to find? Then both the name and the standard ID would lead to the event.

**Comment by lowercasename** [comment]
I've now replaced shortid with nanoid in a new (and merged) PR (https://github.com/lowercasename/gathio/commit/335103a7f94e94f05b656e0193a30e12790a8d38). Adding human-pronounceable URLs has hit a glitch in that the form validator plugin I'm using is deprecated and doesn't appear to support AJAX, so I've forked the beginning of that work into a new PR here: https://github.com/lowercasename/gathio/pull/49

I'm going to close this issue in the meantime - feel free to open another one on pretty/human pronounceable URLs in the meantime if you have any other thoughts.
