### ISSUE TITLE
remove external dependencies

### ISSUE THREAD

**Issue by wxcafe** [lowercasename/gathio#23]
Going to https://gath.io, I see my browser pull a few javascript files and fonts off google or cloudflare. It would be great if we could just host these locally on the server.

**Comment by lowercasename** [comment]
Good idea, this was vaguely on a list of general code tidying fixes I wanted to make but obviously because that list is very long I haven't got around to any of them! I'll do this as a priority because it's very useful for locally hosted instances.

**Comment by lowercasename** [comment]
I've now done this in https://github.com/lowercasename/gathio/commit/111406040ec9f7f48b28077c8eea95a792b14cc7, let me know if you see any missed!

**Comment by wxcafe** [comment]
Hey! Yeah I still see a few:

```
https://fonts.googleapis.com/css?family=Quicksand:400,700
https://fonts.gstatic.com/s/quicksand/v19/6xK-
https://ko-fi.com/widgets/widget_2.js
https://ko-fi.com/img/cup-border.png
```
