### ISSUE TITLE
installation documentation

### ISSUE THREAD

**Issue by wxcafe** [lowercasename/gathio#24]
Getting a step-by-step "how to install this on your own server from scratch" doc would be great. I'm disposed to write this if you want (it's a pretty short documentation too)

**Comment by lowercasename** [comment]
That would be really useful, please do write it! :smiley:

**Comment by wxcafe** [comment]
Here's a first draft


[tmp.txt](https://github.com/lowercasename/gathio/files/4021077/tmp.txt)

**Comment by lowercasename** [comment]
That's perfect, put it in a PR? I would just add why a reverse proxy is useful or add a use case, because this was one of the parts of web development which really confused me when I was getting started, and I didn't know what sort of questions to Google.

**Comment by wxcafe** [comment]
Sure, where would I put it in a PR? I was thinking it could go to the wiki and the README could link to that

Here's an updated version

[tmp.txt](https://github.com/lowercasename/gathio/files/4021226/tmp.txt)

**Comment by lowercasename** [comment]
That's a much better idea than just dumping it in the README, go for it!

**Comment by lowercasename** [comment]
Fantastic, thanks.
