### ISSUE TITLE
Improve Customisation

### ISSUE THREAD

**Issue by bremensaki** [lowercasename/gathio#33]
I've set up an instance, and have noticed that the gath.io name and domain is hard coded in many places. I'm starting to work through these and replace them with values from domain.js - I'll do a proper branch so I can create a PR for this soon when I've got a better sense of the codebase.

Would it be a reasonable approach to define the metadata values used in the event and group views a lot earlier so they're available to things like the front page? It's pretty much entirely derived from the domain.js settings, so I'm thinking it'd be sensible to set up all these things in one hit at the beginning.

Is that workable or is there something else I'm not considering?

**Comment by lowercasename** [comment]
As far as I can think, this is a good idea! @dariusk will be able to say if there are any issues emerging with the ActivityPub/Federation system.

**Comment by dariusk** [comment]
I think this is all fully fixed in the latest master! This was merged a few hours ago so you juuuust missed it.

**Comment by lowercasename** [comment]
Gonna close this, please feel free to reopen.
