### ISSUE TITLE
Unable to register Gath instance at the-federation.info - NodeInfo glitch?

### ISSUE THREAD

**Issue by strypey** [lowercasename/gathio#40]
@light from fediverse.party mentioned being [unable to register a Gath instance](https://git.feneas.org/feneas/fediverse/issues/15#note_9087) at the fediverse monitoring site at [the-federation.info](https://the-federation.info/).

> probably NodeInfo glitch.

Thoughts?

**Comment by lowercasename** [comment]
@dariusk would be best placed to help with this I think but please let me know if there’s a server misconfiguration I can help with! Last I heard I think @dariusk was still hitting some bugs.

**Comment by strypey** [comment]
More info about standards for sharing instance metadata here:
https://talk.feneas.org/t/serviceinfo-specification-for-service-metadata/99

FYI @jaywink ([Jason Robinson of Socialhome](https://medium.com/we-distribute/faces-of-the-federation-jason-robinson-of-socialhome-7f6aa0b77915)) is also the lead dev of the-federation.info and may be able to help if you get stuck with this.

**Comment by lowercasename** [comment]
I've added NodeInfo endpoints for Gathio now!
