### ISSUE TITLE
Any way of email following/notification for new events in group event?

### ISSUE THREAD

**Issue by visoart** [lowercasename/gathio#43]
I was using Gath.io recently and came to a conclusion it would be great to have an option for subscribing to an event group. This way people could send an email address (on the event group) to follow group automatically and get emails about new events.
This feature would keep people in touch with new events.

**Comment by lowercasename** [comment]
I'm all for this. I'd like to spruce up the email notification code a little anyway - this is sort of stuck on me not getting around to adding non-Sendgrid options as noted in  https://github.com/lowercasename/gathio/issues/6. I'll put it on the email todo list!

**Comment by lowercasename** [comment]
I've now added Nodemailer in https://github.com/lowercasename/gathio/commit/b24c5910463453e14be965893cd2a50859a945dd so I'll be looking at this for the next version.

**Comment by rosseljost** [comment]
Love the project so far.

Any ideas on a timeframe for this feature?

Additionally, it would be awesome to have a calendar for a group as well, that way you'd only have to import it once (and if done correctly it updates).

**Comment by lowercasename** [comment]
Hi, and thanks!

At the moment I just can't find the time to work on Gathio - but I am trying to carve out a few hours a month for personal projects, and Gathio will be first on that list.

Explain the calendar concept a bit more? Do you mean a calendar that displays all upcoming events in a group?

**Comment by rosseljost** [comment]
Yes exactly, so on a technical level you'd only have to update the `.ics` file together with the group.
The nice thing is, that (as long as the URL stays the same) you can import an `.ics` file to e.g. Google Calendar via the URL and the calendar periodically checks for updates.
That way you'd only have to import the file once and have an up to date calendar of the group events.

**Comment by sorenpeter** [comment]
An subscribe by email would all still be very handy

**Comment by sorenpeter** [comment]
So it was a bit more complex combining several .ics into one, but i made i work(ish): [algorave.dk/calendar.ics  ](http://algorave.dk/calendar.ics)

**Comment by lowercasename** [comment]
Thanks for your encouragement with this, @sorenpeter! I've 'soft launched' this feature on gath.io - have a look and see if feeds work as you'd expect. I tried with your feed, and that worked in Google Calendar, although a test feed I used didn't seem to show any events, and I can't quite see what the difference is between them.

**Comment by lowercasename** [comment]
The new feature, in case it's not clear, is this feed URL at the bottom of the event group description block:

![Screenshot from 2022-04-23 16-30-36](https://user-images.githubusercontent.com/1748384/164912742-6e7b22f5-b8ba-46a5-bca6-4c93758165ae.png)

That can be copied into Google Calendar or another calendar (it also worked with Gnome Calendar).

**Comment by sorenpeter** [comment]
Hi Rafael, Thank for making this feature.

I am expiring some issues with it:
1. The copy button does not include `https://` so I get an error in both iCal on my Mac and in my google calendar
2. Even when adding the protocol prefix I still get an error in iCal telling me: "The data downloaded from https://gath.io/group/bemYSNYSW4zJ_21bXpOWD/feed.ics isn’t valid." 

On another note, will it be possible to se a nice looking groupe name instead of `bemYSNYSW4zJ_21bXpOWD` ?

**Comment by sorenpeter** [comment]
Hi again. I belive I found the bug for pt. 2 above:
In the feed.ics the last line is `END:VCA` but it should be `END:VCALENDAR`
Correcting this in makes iCal happy.

**Comment by lowercasename** [comment]
Yes, looks like Node is cutting off the last few bytes - will look into it!

**Comment by lowercasename** [comment]
Okay, with the new changes it looks like Google Calendar, at least, is auto-populating the event group name, and gath.io is now returning the entire file without any missing bytes. See how you get on with it!

**Comment by sorenpeter** [comment]
yay, it works in iCal now:)

**Comment by lowercasename** [comment]
I've whipped up a very simple subscribe/unsubscribe to group function:

![image](https://user-images.githubusercontent.com/1748384/165147784-2d038c50-3baa-47f4-937b-a519872b9ec2.png)

There's very little user messaging, which I'll hopefully add later, but I just wanted the basics working for now. When you enter your email and hit 'subscribe', the email is stored on the group and you're emailed a confirmation email. When a new event is added to the group, all subscribers should receive an email with information. And you can unsubscribe from the group by following a link in the email. :smiley:

**Comment by sorenpeter** [comment]
wow, that sounds great:)
