### ISSUE TITLE
ActivityPub code might be preventing old events from being deleted

### ISSUE THREAD

**Issue by lowercasename** [lowercasename/gathio#45]
I've discovered that some old events aren't being deleted on gath.io. I made some very quick bug testing and I _think_ that it might be to do with an error emitted when the server tries to JSON parse the ActivityPub fields of an event without ActivityPub fields. I can look into it, unless @dariusk you have some spare time to poke around at the auto-deleter code? I know you wrote that extra section so you might have a very easy solution.

**Comment by lowercasename** [comment]
Pretty sure I fixed this one now. Old events are now getting deleted when they're meant to be!

**Comment by dariusk** [comment]
Thank you! Sorry I couldn't get around to it.

**Comment by lowercasename** [comment]
No problem at all ❤️
