### ISSUE TITLE
Make email optional when creating events

### ISSUE THREAD

**Issue by cblgh** [lowercasename/gathio#51]
Hi!

I really like the project :)

Forcing people to put in an email address when creating an event does not make sense to me. I've been playing around with using gath.io to create little meeting times for friends. For these types of events, it's not that important to me to get notifications .

Thus, every time I create an event, I have to put in a fake email. (Which probably is extra cruft unneeded for yr backend.)

Consider instead making the email optional, like the already existing functionality when participating in an event.

Thank you all for creating this project! 🖤

**Comment by lowercasename** [comment]
Thank you so much!

The main use for the email in that space is to receive the email containing
the editing password - otherwise the only record of it is shown once when
the event is first displayed, and never again. I feel like removing that by
default will cause more problems (people no longer able to edit their
events) than it will solve (people feeling that supplying an email is
unnecessary). But I'm very willing to listen to other arguments! :)

**Comment by cblgh** [comment]
You still have the secret URL in your browsing history :)

Additionally, I feel like gath could beneficially make use of [localStorage](https://developer.mozilla.org/en-US/docs/Web/API/Window/localStorage) for storing a lot of these things. 

Example:
* I create an event
* the base (normal) and secret URL (edit capabilities) for the event is stored in localStorage
* when I browse to the page's base URL, localStorage is checked to see if we have the secret URL stored

The same localStorage-based functionality could be used for remembering the secret password for removing oneself as an attendee in an event.

Alternately: let pages be editable by anyone by default, and restrict editing by setting a password. A lot of browsers have built-in password managers these days which would likely autoprompt, tho not sure if that is the best. This approach requires a lot more effort, though, than simply making the email optional :)

**Comment by lowercasename** [comment]
Hello! It's been a long time coming, but I'm delighted to say that emails are now optional as of https://github.com/lowercasename/gathio/commit/4ef3273f8bca7ad84140730cea9e7842ee5a0a79.

I've also set up localStorage functionality as suggested here and in https://github.com/lowercasename/gathio/issues/62.

**Comment by cblgh** [comment]
🎉🎉🎉🎉🎉🎉
