### ISSUE TITLE
"Database error, please try again" when creating new event

### ISSUE THREAD

**Issue by sfirke** [lowercasename/gathio#59]
Hi!  I tried to create a new event on gath.io and after filling out all the info, uploading a picture, etc. I got the error message:

> Database error, please try again :( - MongoError: server instance pool was destroyed

Any idea what might be causing that?  Thanks for any help you can provide!

**Comment by lowercasename** [comment]
Hiya! Sorry about this, the server needed a restart. It's working now!

**Comment by sfirke** [comment]
thanks for the quick fix!  :raised_hands:
