### ISSUE TITLE
Additional mail options alongside Sendgrid?

### ISSUE THREAD

**Issue by lowercasename** [lowercasename/gathio#6]
I’d like to hear some thoughts on how to best set up emails, especially for locally hosted instances of gathio. There are a number of issues with Sendgrid:

- It’s paid-for (I’m currently using a free account limited to 100 API calls a day which means that if gathio becomes more popular I’d have to use something else)
- The templates I’m using are locked up in Sendgrid and can’t be accessed or modified by people using gathio locally
- It’s gathio’s only external API dependency, which just seems not totally necessary.

I think it would make sense to set up an optional/default nodemailer route which will use a mail server of the user’s choice, but I’d like to hear thoughts or alternatives!

Also, since I think it makes sense to keep Sendgrid as an option for people without access to a mail server, does anyone know a way to put the Sendgrid templates I’m using on GitHub?

**Comment by MagicFab** [comment]
Pretty much anyone that will be using Gath.io would have at least a personal email account and access to create another one or use the same IMAP / SMTP credentials.
Support for IMAP and JMAP should be an option, and would let a self-hosted solution be coherent with reasons and values involved in using Gath.io.

**Comment by ahstro** [comment]
I'm no email expert, but that nodemailer looks like a simple solution? Just punch in the SMTP config and good to go, or am I missing something?

**Comment by wxcafe** [comment]
using an SMTP server would be great, yeah!

**Comment by lowercasename** [comment]
Nodemailer is finally enabled and set up in https://github.com/lowercasename/gathio/commit/b24c5910463453e14be965893cd2a50859a945dd!
