### ISSUE TITLE
Send Deletion Password to User Email

### ISSUE THREAD

**Issue by XoMEX** [lowercasename/gathio#61]
Hi,
first of all (as in most of the issues) nice project :)

Is there a reason the RSVP deletion password is not included in the "You're RSVPed to" E-Mail? If it was included

- People who supply an E-Mail do not have to remember the password (you could also include a link in the E-Mail. However, this link should require a second confirmation of removal, as users might tend to click on any link they see)
- People who got signed up wrongly can deregister themselves from the E-Mail notifications

**Comment by lowercasename** [comment]
I think this is a great idea and I see no reason why it shouldn't be the case! It can be made very clear to users who don't supply an email that they have no other way to see the deletion password.

**Comment by lowercasename** [comment]
Thanks so much for this - this has now been done in [17d829458b371e478d60d3df843e5123cc61a887](https://github.com/lowercasename/gathio/commit/17d829458b371e478d60d3df843e5123cc61a887)!
