### ISSUE TITLE
Feature request, browser alerts on new event comments, or new event RSVP changes

### ISSUE THREAD

**Issue by JohnTheodore** [lowercasename/gathio#64]
As my first issue, I'd like to start by saying your software is great. I'm very grateful that you made this, and I've enjoyed it with one event so far. I have friends irl, on facebook, on slack, irc, etc, and trying to invite all of these people to one event is difficult. The main event platforms I've seen people use are, facebook, paperless post and eventbrite. Each of these require your email/identity, and remove anonymity. Gath.io solves this, by not requiring registration, which I think is a major key feature that makes this project unique. One major downside to not registering or giving your email to the platform, is that you lose the ability to get notified. While the aforementioned platforms above sacrifice your privacy (by taking your email, keeping the records/logs of what you did) in order to notify you, I don't think these two things are mutually exclusive.  Not being notified, means lower engagement. Engagement for the sake of engagement isn't good. Though when you're hosting an event (from my perspective) a major advantage is drumming up activity, to remind people of the event, if they see people they know are going, they're more likely to want to go, etc. It's not that convenient to have to keep remembering to refresh the gath.io link. ok... so to my proposal. It'd be nice if there was a way to "alert" the browser on event changes. I think making this opt-in would be reasonable, so we don't change any of the default behavior. If the organizer or attendee doesn't want to be nagged, by default they won't. If they want to see who is going and get notified of that, when they first interact with the gath.io link, they can check the option to be notified through the browser. Note, this should work without needing to send any emails. You can change the favicon the way slack does, with a red dot (the current universal notification sybol). Once you click on the tab, the red dot goes away. and, you can be notified on the fly, as say someone RSVPs for your event, libnotify will shoot a message to your browser. 

Thoughts?

**Comment by lowercasename** [comment]
Thank you for this suggestion! I don't mind this being a feature, but it's not a priority for me - I personally dislike browser notifications very much, although I know other people like them and make use of them. If you'd like to write up the code, I'd be happy to review the PR!
