### ISSUE TITLE
Public hosting Web site is down

### ISSUE THREAD

**Issue by iembry** [lowercasename/gathio#69]
Hi, https://gath.io/ is currently down. I'm getting the following error message:

Hmm. We’re having trouble finding that site.

We can’t connect to the server at gath.io.

Thank you.

Irucka

**Comment by lowercasename** [comment]
It looks like this issue and https://github.com/lowercasename/gathio/issues/68 were to do with my nameservers, which seemed to have suffered a memory leak! I've changed the nameservers; can you check if it's working now?

**Comment by AsbjornOlling** [comment]
I'm the creator of #68 - it's working for me again now.

What changed? Did you find out what the issue was?

**Comment by lowercasename** [comment]
Yep, just the comment above!

**Comment by iembry** [comment]
@lowercasename  Yes, it works now. Thank you for fixing the issue so promptly.
