### ISSUE TITLE
Use OpenStreetMap instead of Google Maps

### ISSUE THREAD

**Issue by govvin** [lowercasename/gathio#7]
Since you're trying to promote privacy, have you ever thought of replacing the Find on Google Maps button with OpenStreetMap instead?

**Comment by lowercasename** [comment]
I'm on board with that! Google Maps seems to have a more robust search for badly worded addresses, but I'm sure people can live with that. If @duckinator creates a config file, there could be a simple config option to chose a service for local installs.

**Comment by lowercasename** [comment]
I've put a button for OpenStreetMap on all event pages now! I'm leaving the Google Maps button there as well because at the moment, OSM sadly doesn't recognise a lot of UK postcodes including my own. The postcode data is obviously not open source 🙄
