### ISSUE TITLE
Link to upcomming event under group does not take  you to the event

### ISSUE THREAD

**Issue by sorenpeter** [lowercasename/gathio#72]
Hi lowercasename,

I have just set up an event as part of a group, but the link under "Upcoming Events" only takes you to the gath.io frontpage and not the event. Notice then hover URL in the bottom left corner:
![Screenshot 2022-04-02 at 13 12 54](https://user-images.githubusercontent.com/8458421/161380626-0ea4273d-e703-4b7d-9a06-5fdc674c6709.png)

Evnet: https://gath.io/uVA3cAckHXsRppB0sf551
Group: https://gath.io/group/bemYSNYSW4zJ_21bXpOWD

**Comment by evolverine** [comment]
Same here. And now I can't access my individual events, because I took it for granted I'd be able to through the group 😐

**Comment by lowercasename** [comment]
This sounds like an obvious bug - I'll try looking into it this week, although I'm floored busy, unfortunately. PRs are also super welcome!

**Comment by lowercasename** [comment]
This is now fixed in https://github.com/lowercasename/gathio/commit/66b8062ac5d85bf60214494293dfa33864cdbf10, thanks for reporting!
