### ISSUE TITLE
Feature request: RSVP for number of attendees

### ISSUE THREAD

**Issue by sfirke** [lowercasename/gathio#77]
I love gathio and have been spreading the word.  A family member used it for a child's birthday party and said the one thing they miss from Evite is being able to RSVP for a number of people (children and adults).  That attendee counter is handy for tracking actual guest count, e.g., if someone RSVPs for a family of five then that means more pizza to order than an RSVP for one.

Would love to see this field / capability added as a feature to bring gathio into fuller feature parity.  Thanks for the great product!

**Comment by lowercasename** [comment]
This is a great idea - and should be easy to implement, too! I'll see if I can add it in the next few weeks. 😃

**Comment by sfirke** [comment]
Awesome!  Thanks for implementing, I will give it a shot on my next event.
