### ISSUE TITLE
Ability to add an RSVP/spot limit

### ISSUE THREAD

**Issue by fluffy-critter** [lowercasename/gathio#8]
Hi, it’d be really cool if gath.io supported a guest limit for events - like, only letting the first 10 people to RSVP or whatever. I sometimes have gatherings where there’s only room for so many people and it’s difficult to manage people who are waffling/indecisive and then end up showing up at the last minute despite me saying there’s no room for them anymore or whatever.

Having the “5 spots remaining!” indicator would also be a great motivator to get people to actually decide instead of waiting until the last minute. :)

**Comment by N07070** [comment]
That would be really cool !

**Comment by lowercasename** [comment]
This is a great idea! I'll implement it soon.

**Comment by lowercasename** [comment]
This is live in the latest update, enjoy! You need to click the 'allow attendees' checkbox when creating a new event to make the option come up initially.

**Comment by fluffy-critter** [comment]
Awesome, thanks so much!
