### ISSUE TITLE
Can't register for an event

### ISSUE THREAD

**Issue by amwelles** [lowercasename/gathio#82]
Looks like something is going on with the validation for the "how many people in your party" field. I've entered 1 into that field, and it's showing this error message:

> Please enter a number between 1 and 0

<img width="486" alt="" src="https://user-images.githubusercontent.com/567160/202198385-00669ec8-8790-404f-a5bc-f46e8d059742.png">

I'm going to poke around the codebase and see if I can figure out what's going on.

**Comment by amwelles** [comment]
I pinpointed the problem, but I don't have a way to debug locally. It seems that in this chunk, it's returning 0 for events that don't have an attendee limit.

https://github.com/lowercasename/gathio/blob/master/views/event.handlebars#L585-L587

It looks like this is where that's getting set:

https://github.com/lowercasename/gathio/blob/master/routes.js#L1413-L1415

Proposed solution: wrap the event.handlebars validation in a conditional checking if the event has an attendee limit.

**Comment by raphaelkabo** [comment]
Whoops! I've just fixed this in https://github.com/lowercasename/gathio/commit/e93b23db71df18480b29ed53c1b8247e7f0f83a7 and updated the site. Thank you for the proposed solution, I've done just what you suggested and added some logic bugfixes on the backend.

**Comment by amwelles** [comment]
Perfect, thank you!
