### ISSUE TITLE
Unable to create events on gath.io, 502 Bad Gateway

### ISSUE THREAD

**Issue by N07070** [lowercasename/gathio#9]
Hello,

As I try to create an event on gath.io, once I click on create the event, after entering all the information about the event, I get a 502 Bad Gateway error on the `gath.io/newevent` url. 

I tried using Chromium and Firefox from my computer, and from my phone's Firefox too. 

I hope you can find what's going on. 

Cheers

**Comment by lowercasename** [comment]
Hi! The logs don't show anything useful, unfortunately - the server had a few restarts recently due to another malfunctioning app, so perhaps it was to do with that. Did you end up succeeding in creating an event?

**Comment by lowercasename** [comment]
I'm going to close this due to inactivity - feel free to open it again if you have further issues!
