### ISSUE TITLE
Crash on .avif Cover Photos

### ISSUE THREAD

**Issue by kousu** [lowercasename/gathio#91]
When I try to attach [this](https://user-images.githubusercontent.com/987487/214766976-77d0ae04-8433-41c4-8ed2-9e1f6a3191e2.jpg) cover photo (note: I've renamed its extension to convince GitHub to accept it, but it's actually an AVIF file) I get

```
/srv/gathio/gathio/routes.js:676
        .resize(920, Jimp.AUTO) // resize
         ^
TypeError: Cannot read properties of undefined (reading 'resize')
    at Jimp.<anonymous> (/srv/gathio/gathio/routes.js:676:10)
    at Timeout._onTimeout (/srv/gathio/gathio/node_modules/@jimp/core/dist/index.js:264:25)
    at listOnTimeout (node:internal/timers:568:17)
    at process.processTimers (node:internal/timers:511:7)
Node.js v19.5.0
[nodemon] app crashed - waiting for file changes before starting...
```

I'm running

```
gathio@public:~/gathio$ git show HEAD
commit 8627537af32c8e88fa8bdfe224b92621c7e2df5c (HEAD -> master, origin/master, origin/HEAD)
Merge: e93b23d d39734b
Author: Raphael <raphaelkabo@gmail.com>
Date:   Wed Dec 28 16:38:57 2022 +0000

    Merge pull request #85 from redneckcatholic/fix-event-deletion
    
    Fix event deletion

```

and

```
gathio@public:~/gathio$ npm version
{
  gathio: '1.2.3',
  npm: '9.3.1',
  node: '19.5.0',
  v8: '10.8.168.25-node.11',
  uv: '1.44.2',
  zlib: '1.2.13',
  brotli: '1.0.9',
  ares: '1.18.1',
  modules: '111',
  nghttp2: '1.51.0',
  napi: '8',
  llhttp: '8.1.0',
  uvwasi: '0.0.14',
  acorn: '8.8.1',
  simdutf: '3.1.0',
  undici: '5.14.0',
  openssl: '3.0.7+quic',
  cldr: '42.0',
  icu: '72.1',
  tz: '2022g',
  unicode: '15.0',
  ngtcp2: '0.8.1',
  nghttp3: '0.7.0'
}
```

This takes the whole site down, sadly. I have to `ssh root@example.com systemctl restart gathio` to get it back.

**Comment by lowercasename** [comment]
Thanks for writing this up! I suspect `jimp` doesn't support AVIF files, but the error handling should definitely be better and the file upload field should at least prevent them from being selected, if we can't find a way to support them.

**Comment by kousu** [comment]
Thanks! Just blocking them until `jimp` gets the patch for the new format would be dandy.

**Comment by lowercasename** [comment]
I've improved error handling in the backend and an `allow=` property on the form itself on the frontend in https://github.com/lowercasename/gathio/commit/2e4dbb873372e59dc4bceeca2a8d87460acf2ceb!

**Comment by kousu** [comment]
Wonderful :)
Thanks for being able to find the time for this so quickly!
